name: My First Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      working-directory: backend/save-application
      run: npm install

    - name: Create Lambda ZIP
      working-directory: backend/save-application
      run: zip -r save-application.zip .